services:
  mc-br:
    image: itzg/minecraft-bedrock-server:latest
    container_name: mc-br
    environment:
      EULA: "true"
      TZ: "Asia/Kolkata"
      SERVER_NAME: "Minecraft Bedrock Server"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      ALLOW_CHEATS: "false"
      MAX_PLAYERS: "10"
      SERVER_PORT: "19132"
      SERVER_PORT_V6: "19133"
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
      - ./data:/data
    restart: unless-stopped

  mc-backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mc-backup
    environment:
      TZ: "Asia/Kolkata"
      RETENTION: "10"
      ARCHIVE: "5"
      GDRIVE_ID: ""
      BACKUP_INTERVAL: "1M"
      DISCORD_BOT_TOKEN: ""
      DISCORD_WEBHOOK_URL: ""
      DISCORD_AUTH_ROLES: ""
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ./data:/app/data:ro
      - ./backup:/app/backup
      - ./backup_logs:/app/backup_logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mc-br
    restart: unless-stopped